# Azure pipeline for Terraform AKS module
pool:
  vmImage: 'ubuntu-latest'

variables:
  image_name: terraform-azurerm-aks:$(build.buildId)
  terraform_version: 0.12.10

steps:
  - script: docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${IMAGE_NAME} .
    displayName: 'docker build'

  - script: docker run ${IMAGE_NAME} rake build
    displayName: 'validate'

  - script: docker run $(IMAGE_NAME) rake full
    displayName: 'full build'
    condition: and(succeeded(),eq(variables['build.sourceBranch'], 'refs/heads/master'))